# Generated by Django 4.2.26 on 2026-02-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="كود التطبيق"
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=100, verbose_name="الاسم بالعربية"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=100, verbose_name="الاسم بالإنجليزية"),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-cube", max_length=50, verbose_name="الأيقونة"
                    ),
                ),
                (
                    "module_type",
                    models.CharField(
                        choices=[
                            ("core", "تطبيق أساسي"),
                            ("optional", "تطبيق اختياري"),
                        ],
                        default="optional",
                        max_length=20,
                        verbose_name="نوع التطبيق",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True, verbose_name="مفعّل")),
                (
                    "url_namespace",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="URL Namespace"
                    ),
                ),
                (
                    "menu_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="معرف القائمة"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="الترتيب")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "required_modules",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dependent_modules",
                        to="core.systemmodule",
                        verbose_name="التطبيقات المطلوبة",
                    ),
                ),
            ],
            options={
                "verbose_name": "تطبيق النظام",
                "verbose_name_plural": "تطبيقات النظام",
                "ordering": ["order", "name_ar"],
            },
        ),
    ]
