# Generated by Django 4.2.26 on 2026-02-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unit",
            name="symbol",
        ),
        migrations.AddField(
            model_name="unit",
            name="code",
            field=models.CharField(
                default=0,
                editable=False,
                max_length=10,
                unique=True,
                verbose_name="الكود",
            ),
            preserve_default=False,
        ),
    ]
