# Generated by Django 4.2.26 on 2026-02-27 04:53

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financial", "0002_initial"),
        ("product", "0003_remove_unit_symbol_unit_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voucher_number",
                    models.CharField(
                        blank=True, max_length=50, unique=True, verbose_name="رقم الإذن"
                    ),
                ),
                (
                    "voucher_type",
                    models.CharField(
                        choices=[
                            ("receipt", "إذن استلام جماعي"),
                            ("issue", "إذن صرف جماعي"),
                            ("transfer", "إذن تحويل جماعي"),
                        ],
                        max_length=20,
                        verbose_name="نوع الإذن",
                    ),
                ),
                (
                    "voucher_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاريخ الإذن"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("pending", "معلق"),
                            ("approved", "معتمد"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "purpose_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("donation", "تبرع/هدية واردة"),
                            ("inventory_gain", "زيادة جرد"),
                            ("samples", "عينات مجانية"),
                            ("marketing", "تسويق وإعلان"),
                            ("gifts", "هدايا"),
                            ("damage", "تلف"),
                            ("expired", "منتهي الصلاحية"),
                            ("theft", "سرقة/فقدان"),
                            ("other", "أخرى"),
                        ],
                        max_length=30,
                        null=True,
                        verbose_name="الغرض",
                    ),
                ),
                (
                    "party_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="اسم الجهة"
                    ),
                ),
                (
                    "reference_document",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="المستند المرجعي"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "approval_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الاعتماد"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "total_items",
                    models.PositiveIntegerField(default=0, verbose_name="عدد الأصناف"),
                ),
                (
                    "total_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="إجمالي الكمية"
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="إجمالي القيمة",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batch_vouchers_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="اعتمده",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batch_vouchers_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batch_vouchers",
                        to="financial.journalentry",
                        verbose_name="القيد المحاسبي",
                    ),
                ),
                (
                    "target_warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batch_vouchers_target",
                        to="product.warehouse",
                        verbose_name="المخزن الهدف",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batch_vouchers_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="عدله",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batch_vouchers",
                        to="product.warehouse",
                        verbose_name="المخزن",
                    ),
                ),
            ],
            options={
                "verbose_name": "إذن جماعي",
                "verbose_name_plural": "أذون جماعية",
                "ordering": ["-voucher_date", "-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="purpose_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("donation", "تبرع/هدية واردة"),
                    ("inventory_gain", "زيادة جرد"),
                    ("other", "أخرى"),
                    ("samples", "عينات مجانية"),
                    ("marketing", "تسويق وإعلان"),
                    ("gifts", "هدايا"),
                    ("damage", "تلف"),
                    ("expired", "منتهي الصلاحية"),
                    ("theft", "سرقة/فقدان"),
                    ("other", "أخرى"),
                ],
                help_text="غرض الإذن (يحدد الحساب المحاسبي المقابل)",
                max_length=30,
                null=True,
                verbose_name="غرض الإذن",
            ),
        ),
        migrations.CreateModel(
            name="BatchVoucherItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="الكمية",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="تكلفة الوحدة",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="التكلفة الإجمالية",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "batch_voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="product.batchvoucher",
                        verbose_name="الإذن الجماعي",
                    ),
                ),
                (
                    "inventory_movement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batch_item",
                        to="product.inventorymovement",
                        verbose_name="حركة المخزون",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="product.product",
                        verbose_name="المنتج",
                    ),
                ),
            ],
            options={
                "verbose_name": "بند إذن جماعي",
                "verbose_name_plural": "بنود الأذون الجماعية",
                "ordering": ["batch_voucher", "product"],
                "unique_together": {("batch_voucher", "product")},
            },
        ),
        migrations.AddIndex(
            model_name="batchvoucher",
            index=models.Index(
                fields=["voucher_type", "status"], name="product_bat_voucher_c73974_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batchvoucher",
            index=models.Index(
                fields=["warehouse", "voucher_date"],
                name="product_bat_warehou_b7c058_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="batchvoucher",
            index=models.Index(
                fields=["status", "created_at"], name="product_bat_status_650804_idx"
            ),
        ),
    ]
