# Generated by Django 4.2.26 on 2026-02-27 04:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_batchvoucher_alter_inventorymovement_purpose_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batchvoucher",
            options={
                "ordering": ["-voucher_date", "-created_at"],
                "permissions": [("approve_batchvoucher", "Can approve batch vouchers")],
                "verbose_name": "إذن جماعي",
                "verbose_name_plural": "أذون جماعية",
            },
        ),
    ]
