# Generated by Django 4.2.26 on 2026-02-27 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_alter_batchvoucher_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorymovement",
            name="batch_voucher",
            field=models.ForeignKey(
                blank=True,
                help_text="الإذن الجماعي الذي أنشأ هذه الحركة (إن وجد)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_movements",
                to="product.batchvoucher",
                verbose_name="الإذن الجماعي",
            ),
        ),
    ]
