# Generated by Django 4.2.26 on 2026-02-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_add_batch_voucher_link_to_inventory_movement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorymovement",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("purchase", "شراء"),
                    ("sale", "بيع"),
                    ("transfer", "تحويل"),
                    ("adjustment", "تسوية"),
                    ("return", "مرتجع"),
                    ("damage", "إتلاف"),
                    ("opening", "رصيد افتتاحي"),
                    ("manual", "يدوي"),
                    ("receipt_voucher", "إذن استلام"),
                    ("issue_voucher", "إذن صرف"),
                ],
                default="manual",
                max_length=50,
                verbose_name="نوع المستند",
            ),
        ),
    ]
