# Generated by Django 4.2.26 on 2026-02-27 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financial", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audittrail",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="audittrail",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="accountingperiod",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "سنة مالية",
                "verbose_name_plural": "السنوات المالية",
            },
        ),
        migrations.AddField(
            model_name="accountingperiod",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="وصف أو ملاحظات عن السنة المالية",
                null=True,
                verbose_name="الوصف",
            ),
        ),
        migrations.AddField(
            model_name="accountingperiod",
            name="fiscal_year",
            field=models.CharField(
                default=0,
                help_text="مثال: 2024-2025 أو 2024",
                max_length=20,
                unique=True,
                verbose_name="السنة المالية",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="accountingperiod",
            name="is_current",
            field=models.BooleanField(
                default=False,
                help_text="هل هذه هي السنة المالية الحالية؟",
                verbose_name="السنة الحالية",
            ),
        ),
        migrations.AddField(
            model_name="accountingperiod",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
        ),
        migrations.AlterField(
            model_name="accountingperiod",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fiscal_years_closed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أغلق بواسطة",
            ),
        ),
        migrations.AlterField(
            model_name="accountingperiod",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fiscal_years_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AlterField(
            model_name="accountingperiod",
            name="end_date",
            field=models.DateField(
                help_text="تاريخ نهاية السنة المالية", verbose_name="تاريخ النهاية"
            ),
        ),
        migrations.AlterField(
            model_name="accountingperiod",
            name="name",
            field=models.CharField(
                help_text="مثال: السنة المالية 2024-2025",
                max_length=100,
                verbose_name="اسم السنة المالية",
            ),
        ),
        migrations.AlterField(
            model_name="accountingperiod",
            name="start_date",
            field=models.DateField(
                help_text="تاريخ بداية السنة المالية", verbose_name="تاريخ البداية"
            ),
        ),
        migrations.AddIndex(
            model_name="accountingperiod",
            index=models.Index(
                fields=["fiscal_year"], name="financial_a_fiscal__2ed213_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accountingperiod",
            index=models.Index(
                fields=["start_date", "end_date"], name="financial_a_start_d_db19fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accountingperiod",
            index=models.Index(
                fields=["status", "is_current"], name="financial_a_status_8e1bce_idx"
            ),
        ),
        migrations.DeleteModel(
            name="AuditTrail",
        ),
    ]
