# Generated by Django 4.2.26 on 2026-02-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditTrail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Name of the model being audited", max_length=100
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        help_text="ID of the object being audited"
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("VIEW", "View"),
                            ("ADMIN_ACCESS", "Admin Access"),
                            ("AUTHORITY_VIOLATION", "Authority Violation"),
                        ],
                        help_text="Type of operation performed",
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "before_data",
                    models.JSONField(
                        blank=True, help_text="Data before the operation", null=True
                    ),
                ),
                (
                    "after_data",
                    models.JSONField(
                        blank=True, help_text="Data after the operation", null=True
                    ),
                ),
                (
                    "source_service",
                    models.CharField(
                        help_text="Service that initiated the operation", max_length=100
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the user", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="User agent string", null=True
                    ),
                ),
                (
                    "additional_context",
                    models.JSONField(
                        blank=True,
                        help_text="Additional context information",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Trail",
                "verbose_name_plural": "Audit Trails",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AuthorityDelegation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_service",
                    models.CharField(
                        help_text="Service delegating authority", max_length=100
                    ),
                ),
                (
                    "to_service",
                    models.CharField(
                        help_text="Service receiving authority", max_length=100
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Model for which authority is delegated",
                        max_length=100,
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When this delegation expires"),
                ),
                ("reason", models.TextField(help_text="Reason for delegation")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this delegation is currently active",
                    ),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Authority Delegation",
                "verbose_name_plural": "Authority Delegations",
                "ordering": ["-granted_at"],
            },
        ),
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        help_text="Type of operation (e.g., 'journal_entry', 'stock_movement')",
                        max_length=100,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        help_text="Unique key for this operation", max_length=255
                    ),
                ),
                (
                    "result_data",
                    models.JSONField(help_text="Serialized result of the operation"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When this idempotency record expires"
                    ),
                ),
            ],
            options={
                "verbose_name": "Idempotency Record",
                "verbose_name_plural": "Idempotency Records",
            },
        ),
        migrations.CreateModel(
            name="QuarantineRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Name of the model containing corrupted data",
                        max_length=100,
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(help_text="ID of the corrupted object"),
                ),
                (
                    "corruption_type",
                    models.CharField(
                        choices=[
                            ("ORPHANED_ENTRY", "Orphaned Journal Entry"),
                            ("NEGATIVE_STOCK", "Negative Stock"),
                            ("UNBALANCED_ENTRY", "Unbalanced Journal Entry"),
                            ("MULTIPLE_ACTIVE_YEAR", "Multiple Active Academic Years"),
                            ("INVALID_SOURCE_LINK", "Invalid Source Linkage"),
                            ("AUTHORITY_VIOLATION", "Authority Boundary Violation"),
                            ("SUSPICIOUS_PATTERN", "Suspicious Data Pattern"),
                        ],
                        help_text="Type of corruption detected",
                        max_length=100,
                    ),
                ),
                (
                    "original_data",
                    models.JSONField(help_text="Original data before quarantine"),
                ),
                (
                    "quarantine_reason",
                    models.TextField(help_text="Detailed reason for quarantine"),
                ),
                ("quarantined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUARANTINED", "Quarantined"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("RESOLVED", "Resolved"),
                            ("PERMANENT", "Permanent Quarantine"),
                        ],
                        default="QUARANTINED",
                        max_length=50,
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(
                        blank=True, help_text="Notes about resolution", null=True
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Quarantine Record",
                "verbose_name_plural": "Quarantine Records",
                "ordering": ["-quarantined_at"],
            },
        ),
    ]
