# Generated by Django 4.2.26 on 2026-02-26 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("governance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quarantinerecord",
            name="quarantined_by",
            field=models.ForeignKey(
                help_text="User or system that quarantined the data",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quarantined_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="quarantinerecord",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resolved_quarantine_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="idempotencyrecord",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who initiated the operation",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_idempotency_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="authoritydelegation",
            name="granted_by",
            field=models.ForeignKey(
                help_text="User who granted the delegation",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="granted_authority_delegations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="authoritydelegation",
            name="revoked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revoked_authority_delegations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="audittrail",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who performed the operation (null for system operations)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="governance_audit_trails",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="quarantinerecord",
            index=models.Index(
                fields=["model_name", "object_id"],
                name="governance__model_n_46026e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="quarantinerecord",
            index=models.Index(
                fields=["corruption_type", "status"],
                name="governance__corrupt_6d8ed2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="quarantinerecord",
            index=models.Index(
                fields=["quarantined_at"], name="governance__quarant_a51434_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quarantinerecord",
            index=models.Index(fields=["status"], name="governance__status_d525ec_idx"),
        ),
        migrations.AddIndex(
            model_name="idempotencyrecord",
            index=models.Index(
                fields=["operation_type", "idempotency_key"],
                name="governance__operati_19bbc3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="idempotencyrecord",
            index=models.Index(
                fields=["expires_at"], name="governance__expires_557490_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="idempotencyrecord",
            index=models.Index(
                fields=["created_at"], name="governance__created_0af0e3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="idempotencyrecord",
            unique_together={("operation_type", "idempotency_key")},
        ),
        migrations.AddIndex(
            model_name="authoritydelegation",
            index=models.Index(
                fields=["from_service", "to_service", "model_name"],
                name="governance__from_se_bedaa4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="authoritydelegation",
            index=models.Index(
                fields=["expires_at", "is_active"],
                name="governance__expires_429947_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="authoritydelegation",
            index=models.Index(
                fields=["granted_at"], name="governance__granted_f06bd9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["model_name", "object_id"],
                name="governance__model_n_3ab51c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["user", "timestamp"], name="governance__user_id_72d2a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["operation", "timestamp"], name="governance__operati_a05589_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["source_service", "timestamp"],
                name="governance__source__ebee84_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["timestamp"], name="governance__timesta_aaedf6_idx"
            ),
        ),
    ]
