# Generated by Django 4.2.26 on 2026-02-27 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("governance", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="audittrail",
            name="resolution_notes",
            field=models.TextField(
                blank=True, help_text="Notes about the resolution", null=True
            ),
        ),
        migrations.AddField(
            model_name="audittrail",
            name="resolution_status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("RESOLVED", "Resolved"),
                    ("IGNORED", "Ignored"),
                    ("AUTO_RESOLVED", "Auto Resolved"),
                ],
                default="ACTIVE",
                help_text="Resolution status for exceptions and violations",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="audittrail",
            name="resolved_at",
            field=models.DateTimeField(
                blank=True, help_text="When the issue was resolved", null=True
            ),
        ),
        migrations.AddField(
            model_name="audittrail",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who marked this as resolved",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_audit_trails",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="audittrail",
            name="operation",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                    ("VIEW", "View"),
                    ("ADMIN_ACCESS", "Admin Access"),
                    ("AUTHORITY_VIOLATION", "Authority Violation"),
                    ("EXCEPTION", "Exception"),
                    ("ENFORCE_IMMUTABILITY", "Enforce Immutability"),
                ],
                help_text="Type of operation performed",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["resolution_status", "operation"],
                name="governance__resolut_7b86d2_idx",
            ),
        ),
    ]
