# Generated by Django 4.2.26 on 2026-02-27 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("governance", "0003_audittrail_resolution_notes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("PASSWORD_ENCRYPTION", "تشفير كلمات المرور"),
                            ("SESSION_TIMEOUT", "انتهاء الجلسة"),
                            ("BRUTE_FORCE_PROTECTION", "حماية من البروت فورس"),
                            ("RATE_LIMITING", "تحديد معدل الطلبات"),
                            ("IP_WHITELIST", "قائمة IP البيضاء"),
                            ("TWO_FACTOR_AUTH", "المصادقة الثنائية"),
                            ("PASSWORD_POLICY", "سياسة كلمات المرور"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="نوع السياسة",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True, verbose_name="مفعل")),
                (
                    "configuration",
                    models.JSONField(default=dict, verbose_name="الإعدادات"),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_policies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم التحديث بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "سياسة أمنية",
                "verbose_name_plural": "السياسات الأمنية",
                "ordering": ["policy_type"],
            },
        ),
        migrations.CreateModel(
            name="SecurityIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("FAILED_LOGIN", "محاولة دخول فاشلة"),
                            ("UNAUTHORIZED_ACCESS", "وصول غير مصرح"),
                            ("SUSPICIOUS_ACTIVITY", "نشاط مشبوه"),
                            ("BRUTE_FORCE", "هجوم بروت فورس"),
                            ("SQL_INJECTION", "محاولة SQL Injection"),
                            ("XSS_ATTEMPT", "محاولة XSS"),
                            ("CSRF_VIOLATION", "انتهاك CSRF"),
                            ("RATE_LIMIT_EXCEEDED", "تجاوز حد الطلبات"),
                            ("PERMISSION_VIOLATION", "انتهاك صلاحيات"),
                            ("DATA_BREACH_ATTEMPT", "محاولة اختراق بيانات"),
                        ],
                        max_length=50,
                        verbose_name="نوع الحادث",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "منخفض"),
                            ("MEDIUM", "متوسط"),
                            ("HIGH", "عالي"),
                            ("CRITICAL", "حرج"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                        verbose_name="الخطورة",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "نشط"),
                            ("UNDER_REVIEW", "قيد المراجعة"),
                            ("RESOLVED", "تم الحل"),
                            ("FALSE_POSITIVE", "إنذار خاطئ"),
                            ("IGNORED", "تم التجاهل"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="عنوان IP")),
                (
                    "username_attempted",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="اسم المستخدم المحاول"
                    ),
                ),
                ("description", models.TextField(verbose_name="الوصف")),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "request_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="مسار الطلب"
                    ),
                ),
                (
                    "request_method",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="نوع الطلب"
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="وقت الاكتشاف"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الحل"
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(blank=True, verbose_name="ملاحظات الحل"),
                ),
                (
                    "additional_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="بيانات إضافية"
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_incidents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الحل بواسطة",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_incidents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "حادث أمني",
                "verbose_name_plural": "الحوادث الأمنية",
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(
                        fields=["-detected_at"], name="governance__detecte_40f286_idx"
                    ),
                    models.Index(
                        fields=["status", "-detected_at"],
                        name="governance__status_1e935d_idx",
                    ),
                    models.Index(
                        fields=["severity", "-detected_at"],
                        name="governance__severit_130c33_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "-detected_at"],
                        name="governance__ip_addr_0dc0c3_idx",
                    ),
                    models.Index(
                        fields=["incident_type", "-detected_at"],
                        name="governance__inciden_fb2118_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BlockedIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(unique=True, verbose_name="عنوان IP"),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("BRUTE_FORCE", "هجوم بروت فورس"),
                            ("SUSPICIOUS_ACTIVITY", "نشاط مشبوه"),
                            ("MANUAL_BLOCK", "حجب يدوي"),
                            ("AUTO_BLOCK", "حجب تلقائي"),
                            ("REPEATED_VIOLATIONS", "انتهاكات متكررة"),
                        ],
                        max_length=50,
                        verbose_name="السبب",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "blocked_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الحجب"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "unblocked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ إلغاء الحجب"
                    ),
                ),
                (
                    "attempts_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد المحاولات"
                    ),
                ),
                (
                    "last_attempt_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر محاولة"
                    ),
                ),
                (
                    "blocked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blocked_ips",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الحجب بواسطة",
                    ),
                ),
                (
                    "unblocked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unblocked_ips",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم إلغاء الحجب بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "عنوان IP محجوب",
                "verbose_name_plural": "عناوين IP المحجوبة",
                "ordering": ["-blocked_at"],
                "indexes": [
                    models.Index(
                        fields=["ip_address", "is_active"],
                        name="governance__ip_addr_7d0d8e_idx",
                    ),
                    models.Index(
                        fields=["-blocked_at"], name="governance__blocked_226c89_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ActiveSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="مفتاح الجلسة"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="عنوان IP")),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "login_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت الدخول"),
                ),
                (
                    "last_activity",
                    models.DateTimeField(auto_now=True, verbose_name="آخر نشاط"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "terminated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الإنهاء"
                    ),
                ),
                (
                    "terminated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="terminated_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الإنهاء بواسطة",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "جلسة نشطة",
                "verbose_name_plural": "الجلسات النشطة",
                "ordering": ["-login_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="governance__user_id_9bad3c_idx",
                    ),
                    models.Index(
                        fields=["session_key"], name="governance__session_0f9a8d_idx"
                    ),
                    models.Index(
                        fields=["-last_activity"], name="governance__last_ac_f833a9_idx"
                    ),
                ],
            },
        ),
    ]
