# Generated by Django 4.2.26 on 2026-02-27 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("governance", "0004_securitypolicy_securityincident_blockedip_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("LOGIN_SUCCESS", "تسجيل دخول ناجح"),
                            ("LOGIN_FAILED", "محاولة دخول فاشلة"),
                            ("ACCOUNT_LOCKED", "حساب مقفل"),
                            ("SESSION_CREATED", "جلسة جديدة"),
                            ("SESSION_TERMINATED", "جلسة منتهية"),
                            ("SECURITY_SCAN", "فحص أمني"),
                            ("KEY_ROTATION", "تدوير مفتاح"),
                            ("POLICY_UPDATE", "تحديث سياسة"),
                            ("INCIDENT_DETECTED", "حادث أمني"),
                            ("INCIDENT_RESOLVED", "حل حادث"),
                        ],
                        max_length=50,
                        verbose_name="نوع المقياس",
                    ),
                ),
                ("value", models.IntegerField(default=1, verbose_name="القيمة")),
                (
                    "recorded_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="تاريخ التسجيل"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True, db_index=True, verbose_name="التاريخ"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="عنوان IP"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="بيانات إضافية"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_metrics",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "مقياس أمني",
                "verbose_name_plural": "المقاييس الأمنية",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["metric_type", "-recorded_at"],
                        name="governance__metric__b2046a_idx",
                    ),
                    models.Index(
                        fields=["date", "metric_type"],
                        name="governance__date_d39d14_idx",
                    ),
                    models.Index(
                        fields=["-recorded_at"], name="governance__recorde_9d65f0_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EncryptionKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم المفتاح"
                    ),
                ),
                (
                    "key_type",
                    models.CharField(
                        choices=[
                            ("AES-128", "AES-128"),
                            ("AES-256", "AES-256"),
                            ("RSA-2048", "RSA-2048"),
                            ("RSA-4096", "RSA-4096"),
                        ],
                        max_length=20,
                        verbose_name="نوع التشفير",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "نشط"),
                            ("EXPIRING_SOON", "قريب الانتهاء"),
                            ("EXPIRED", "منتهي"),
                            ("ROTATED", "تم التدوير"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        help_text="Hash للمفتاح - ليس المفتاح نفسه",
                        max_length=255,
                        verbose_name="Hash المفتاح",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="تاريخ الانتهاء")),
                (
                    "rotated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ التدوير"
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد مرات الاستخدام"
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر استخدام"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_encryption_keys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الإنشاء بواسطة",
                    ),
                ),
                (
                    "rotated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rotated_encryption_keys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم التدوير بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مفتاح تشفير",
                "verbose_name_plural": "مفاتيح التشفير",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["key_name", "status"],
                        name="governance__key_nam_f07515_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="governance__status_337c94_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="governance__expires_efadcc_idx"
                    ),
                ],
            },
        ),
    ]
