# Generated by Django 4.2.26 on 2026-02-27 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("governance", "0005_securitymetric_encryptionkey"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignalRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signal_name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="اسم الإشارة"
                    ),
                ),
                (
                    "signal_type",
                    models.CharField(
                        choices=[
                            ("post_save", "Post Save"),
                            ("pre_save", "Pre Save"),
                            ("post_delete", "Post Delete"),
                            ("pre_delete", "Pre Delete"),
                            ("m2m_changed", "M2M Changed"),
                            ("custom", "Custom Signal"),
                        ],
                        max_length=20,
                        verbose_name="نوع الإشارة",
                    ),
                ),
                (
                    "module_name",
                    models.CharField(max_length=100, verbose_name="اسم الموديول"),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="اسم الموديل"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "منخفض"),
                            ("MEDIUM", "متوسط"),
                            ("HIGH", "عالي"),
                            ("CRITICAL", "حرج"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                        verbose_name="الأولوية",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "نشط"),
                            ("DISABLED", "معطل"),
                            ("PAUSED", "متوقف مؤقتاً"),
                            ("ERROR", "خطأ"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                ("is_critical", models.BooleanField(default=False, verbose_name="حرج")),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "handler_function",
                    models.CharField(max_length=200, verbose_name="دالة المعالج"),
                ),
                (
                    "registered_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التسجيل"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
                (
                    "max_execution_time_ms",
                    models.IntegerField(
                        default=1000, verbose_name="الحد الأقصى لوقت التنفيذ (ms)"
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل إشارة",
                "verbose_name_plural": "سجل الإشارات",
                "ordering": ["module_name", "signal_name"],
                "indexes": [
                    models.Index(
                        fields=["signal_name"], name="governance__signal__330cc2_idx"
                    ),
                    models.Index(
                        fields=["module_name", "status"],
                        name="governance__module__e0be07_idx",
                    ),
                    models.Index(
                        fields=["status", "is_critical"],
                        name="governance__status_b1aa39_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SignalPerformanceAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("SLOW_EXECUTION", "تنفيذ بطيء"),
                            ("HIGH_FAILURE_RATE", "معدل فشل عالي"),
                            ("TIMEOUT", "انتهاء المهلة"),
                            ("REPEATED_ERRORS", "أخطاء متكررة"),
                            ("CRITICAL_FAILURE", "فشل حرج"),
                        ],
                        max_length=50,
                        verbose_name="نوع التنبيه",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "معلومة"),
                            ("WARNING", "تحذير"),
                            ("ERROR", "خطأ"),
                            ("CRITICAL", "حرج"),
                        ],
                        max_length=20,
                        verbose_name="الخطورة",
                    ),
                ),
                ("message", models.TextField(verbose_name="الرسالة")),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="التفاصيل"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="تم الحل"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الحل"
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_signal_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الحل بواسطة",
                    ),
                ),
                (
                    "signal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="governance.signalregistry",
                        verbose_name="الإشارة",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنبيه أداء إشارة",
                "verbose_name_plural": "تنبيهات أداء الإشارات",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["signal", "-created_at"],
                        name="governance__signal__b82be3_idx",
                    ),
                    models.Index(
                        fields=["is_resolved", "-created_at"],
                        name="governance__is_reso_3548ee_idx",
                    ),
                    models.Index(
                        fields=["severity", "-created_at"],
                        name="governance__severit_40d843_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SignalExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "نجح"),
                            ("FAILED", "فشل"),
                            ("TIMEOUT", "انتهت المهلة"),
                            ("SKIPPED", "تم التخطي"),
                        ],
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="وقت التنفيذ"
                    ),
                ),
                (
                    "execution_time_ms",
                    models.IntegerField(verbose_name="وقت التنفيذ (ms)"),
                ),
                (
                    "instance_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="معرف الكائن"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="رسالة الخطأ"),
                ),
                (
                    "error_traceback",
                    models.TextField(blank=True, verbose_name="تتبع الخطأ"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="بيانات إضافية"
                    ),
                ),
                (
                    "signal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="governance.signalregistry",
                        verbose_name="الإشارة",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signal_executions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنفيذ إشارة",
                "verbose_name_plural": "تنفيذات الإشارات",
                "ordering": ["-executed_at"],
                "indexes": [
                    models.Index(
                        fields=["signal", "-executed_at"],
                        name="governance__signal__21b269_idx",
                    ),
                    models.Index(
                        fields=["status", "-executed_at"],
                        name="governance__status_1e3863_idx",
                    ),
                    models.Index(
                        fields=["-executed_at"], name="governance__execute_bdddb8_idx"
                    ),
                    models.Index(
                        fields=["signal", "status"],
                        name="governance__signal__26f82e_idx",
                    ),
                ],
            },
        ),
    ]
