# Generated by Django 4.2.26 on 2026-02-27 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("governance", "0006_signalregistry_signalperformancealert_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم التقرير")),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("table", "جدول"),
                            ("bar", "رسم بياني عمودي"),
                            ("pie", "رسم دائري"),
                            ("line", "رسم خطي"),
                            ("summary", "ملخص إحصائي"),
                        ],
                        max_length=20,
                        verbose_name="نوع التقرير",
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        choices=[
                            ("customers", "العملاء"),
                            ("invoices", "الفواتير"),
                            ("payments", "المدفوعات"),
                            ("activities", "الأنشطة"),
                            ("transportation", "النقل"),
                            ("hr", "الموارد البشرية"),
                            ("financial", "المالية"),
                            ("inventory", "المخزون"),
                        ],
                        max_length=50,
                        verbose_name="مصدر البيانات",
                    ),
                ),
                (
                    "selected_fields",
                    models.JSONField(default=list, verbose_name="الحقول المختارة"),
                ),
                ("filters", models.JSONField(default=dict, verbose_name="المرشحات")),
                (
                    "group_by",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="التجميع حسب"
                    ),
                ),
                (
                    "sort_by",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="الترتيب حسب"
                    ),
                ),
                (
                    "sort_order",
                    models.CharField(
                        choices=[("asc", "تصاعدي"), ("desc", "تنازلي")],
                        default="asc",
                        max_length=10,
                        verbose_name="اتجاه الترتيب",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "last_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر تشغيل"
                    ),
                ),
                (
                    "run_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد مرات التشغيل"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "نشط"),
                            ("INACTIVE", "غير نشط"),
                            ("ARCHIVED", "مؤرشف"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                ("is_public", models.BooleanField(default=False, verbose_name="عام")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الإنشاء بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "تقرير محفوظ",
                "verbose_name_plural": "التقارير المحفوظة",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "يومياً"),
                            ("weekly", "أسبوعياً"),
                            ("monthly", "شهرياً"),
                            ("quarterly", "ربع سنوي"),
                        ],
                        max_length=20,
                        verbose_name="التكرار",
                    ),
                ),
                ("schedule_time", models.TimeField(verbose_name="وقت التشغيل")),
                (
                    "day_of_week",
                    models.IntegerField(
                        blank=True,
                        help_text="0=الاثنين, 6=الأحد",
                        null=True,
                        verbose_name="يوم الأسبوع",
                    ),
                ),
                (
                    "day_of_month",
                    models.IntegerField(
                        blank=True,
                        help_text="1-31",
                        null=True,
                        verbose_name="يوم الشهر",
                    ),
                ),
                (
                    "email_recipients",
                    models.TextField(
                        help_text="عناوين البريد الإلكتروني مفصولة بفواصل",
                        verbose_name="المستلمون",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "نشط"),
                            ("PAUSED", "متوقف مؤقتاً"),
                            ("DISABLED", "معطل"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "last_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر تشغيل"
                    ),
                ),
                (
                    "next_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="التشغيل التالي"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الإنشاء بواسطة",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="governance.savedreport",
                        verbose_name="التقرير",
                    ),
                ),
            ],
            options={
                "verbose_name": "جدولة تقرير",
                "verbose_name_plural": "جدولة التقارير",
                "ordering": ["next_run_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "قيد الانتظار"),
                            ("RUNNING", "قيد التشغيل"),
                            ("SUCCESS", "نجح"),
                            ("FAILED", "فشل"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت البدء"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الانتهاء"
                    ),
                ),
                (
                    "execution_time_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="وقت التنفيذ (ms)"
                    ),
                ),
                (
                    "rows_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="عدد الصفوف"
                    ),
                ),
                (
                    "result_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="بيانات النتيجة"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="رسالة الخطأ"),
                ),
                (
                    "error_traceback",
                    models.TextField(blank=True, verbose_name="تتبع الخطأ"),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="governance.savedreport",
                        verbose_name="التقرير",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executions",
                        to="governance.reportschedule",
                        verbose_name="الجدولة",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_executions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم التشغيل بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنفيذ تقرير",
                "verbose_name_plural": "تنفيذات التقارير",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="savedreport",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="governance__created_f8c986_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="savedreport",
            index=models.Index(
                fields=["data_source", "status"], name="governance__data_so_0c735b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savedreport",
            index=models.Index(
                fields=["status", "-last_run_at"], name="governance__status_ec4979_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportschedule",
            index=models.Index(
                fields=["status", "next_run_at"], name="governance__status_cccb88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportschedule",
            index=models.Index(
                fields=["report", "-created_at"], name="governance__report__7ebd01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportexecution",
            index=models.Index(
                fields=["report", "-started_at"], name="governance__report__d36261_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportexecution",
            index=models.Index(
                fields=["status", "-started_at"], name="governance__status_3c423b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportexecution",
            index=models.Index(
                fields=["-started_at"], name="governance__started_dc561c_idx"
            ),
        ),
    ]
