# Generated by Django 4.2.26 on 2026-02-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("governance", "0008_alter_savedreport_data_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedreport",
            name="data_source",
            field=models.CharField(
                choices=[
                    ("customers", "العملاء"),
                    ("sales", "فواتير المبيعات"),
                    ("purchases", "فواتير المشتريات"),
                    ("payments", "المدفوعات"),
                    ("employees", "الموظفين"),
                    ("journal_entries", "القيود اليومية"),
                    ("products", "المنتجات"),
                    ("suppliers", "الموردين"),
                ],
                max_length=50,
                verbose_name="مصدر البيانات",
            ),
        ),
    ]
