# Generated by Django 4.2.26 on 2026-02-26 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DriverPricingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_cost_per_student",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="التكلفة الشهرية السابقة للطالب الواحد",
                        max_digits=8,
                        null=True,
                        verbose_name="التكلفة السابقة للطالب",
                    ),
                ),
                (
                    "new_cost_per_student",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="التكلفة الشهرية الجديدة للطالب الواحد",
                        max_digits=8,
                        verbose_name="التكلفة الجديدة للطالب",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        help_text="تاريخ بداية سريان التكلفة الجديدة",
                        verbose_name="تاريخ السريان",
                    ),
                ),
                (
                    "change_reason",
                    models.TextField(
                        blank=True,
                        help_text="سبب تغيير التسعيرة",
                        verbose_name="سبب التغيير",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "تاريخ تغيير تسعيرة السائق",
                "verbose_name_plural": "تاريخ تغييرات تسعيرة السائقين",
                "ordering": ["-effective_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyDriverInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.PositiveIntegerField(
                        help_text="رقم الشهر (1-12)", verbose_name="الشهر"
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        help_text="السنة الميلادية", verbose_name="السنة"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="الكمية أو عدد الوحدات في هذا الشهر",
                        max_digits=6,
                        verbose_name="الكمية",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="التكلفة الشهرية للوحدة الواحدة وقت إنشاء الفاتورة",
                        max_digits=8,
                        verbose_name="التكلفة للوحدة",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="إجمالي مبلغ الفاتورة (الكمية × التكلفة للوحدة)",
                        max_digits=10,
                        verbose_name="المبلغ الإجمالي",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generated", "مولدة"),
                            ("confirmed", "مؤكدة"),
                            ("paid", "مدفوعة"),
                            ("cancelled", "ملغية"),
                        ],
                        default="generated",
                        max_length=20,
                        verbose_name="حالة الفاتورة",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="ملاحظات إضافية حول الفاتورة",
                        verbose_name="ملاحظات",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التوليد"
                    ),
                ),
            ],
            options={
                "verbose_name": "فاتورة سائق شهرية",
                "verbose_name_plural": "فواتير السائقين الشهرية",
                "ordering": ["-year", "-month", "driver_supplier__name"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="اسم المورد")),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="يجب أن يكون رقم الهاتف بالصيغة: '+999999999'. يسمح بـ 15 رقم كحد أقصى.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="رقم الهاتف",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="العنوان"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="البريد الإلكتروني",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="كود المورد",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="الشخص المسؤول",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="الرصيد الحالي",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "tax_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="الرقم الضريبي",
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, verbose_name="الموقع الإلكتروني"),
                ),
                (
                    "whatsapp",
                    models.CharField(blank=True, max_length=20, verbose_name="واتساب"),
                ),
                (
                    "secondary_phone",
                    models.CharField(
                        blank=True, max_length=17, verbose_name="هاتف ثانوي"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="المدينة"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default="مصر", max_length=100, verbose_name="البلد"
                    ),
                ),
                (
                    "working_hours",
                    models.CharField(
                        blank=True,
                        help_text="مثال: من 9 صباحاً إلى 5 مساءً",
                        max_length=100,
                        verbose_name="ساعات العمل",
                    ),
                ),
                (
                    "is_preferred",
                    models.BooleanField(
                        default=False,
                        help_text="هل هذا مورد مفضل للشركة؟",
                        verbose_name="مورد مفضل",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="تاريخ التحديث"
                    ),
                ),
            ],
            options={
                "verbose_name": "مورد",
                "verbose_name_plural": "الموردين",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SupplierType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم النوع")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="الرمز"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, unique=True, verbose_name="الرابط"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="وصف")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="اسم الأيقونة من Font Awesome",
                        max_length=50,
                        verbose_name="أيقونة",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#007bff",
                        help_text="لون بصيغة HEX",
                        max_length=7,
                        verbose_name="لون",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتيب العرض"),
                ),
            ],
            options={
                "verbose_name": "نوع مورد",
                "verbose_name_plural": "أنواع الموردين",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SupplierTypeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="اسم نوع المورد كما سيظهر في الواجهة",
                        max_length=100,
                        verbose_name="اسم النوع",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="رمز فريد لنوع المورد (بالإنجليزية)",
                        max_length=50,
                        unique=True,
                        verbose_name="الرمز",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="وصف مختصر لنوع المورد",
                        verbose_name="الوصف",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-truck",
                        help_text="اسم الأيقونة من Font Awesome (مثل: fas fa-truck)",
                        max_length=50,
                        verbose_name="الأيقونة",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#007bff",
                        help_text="لون النوع بصيغة HEX (مثل: #007bff)",
                        max_length=7,
                        verbose_name="اللون",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="ترتيب ظهور النوع في القوائم",
                        verbose_name="ترتيب العرض",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="هل النوع نشط ويظهر في الواجهة؟",
                        verbose_name="نشط",
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="الأنواع الأساسية التي لا يمكن حذفها",
                        verbose_name="نوع نظام",
                    ),
                ),
                (
                    "is_service_provider",
                    models.BooleanField(
                        default=False,
                        help_text="هل هذا المورد يقدم خدمات (بدون مخزون) أم منتجات (تحتاج مخزون)؟",
                        verbose_name="مقدم خدمات",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="تاريخ التحديث"
                    ),
                ),
            ],
            options={
                "verbose_name": "إعدادات نوع المورد",
                "verbose_name_plural": "إعدادات أنواع الموردين",
                "db_table": "supplier_type_settings",
                "ordering": ["display_order", "name"],
            },
        ),
    ]
