# Generated by Django 4.2.26 on 2026-02-26 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("supplier", "0001_initial"),
        ("financial", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("purchase", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="suppliertypesettings",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_supplier_types",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="suppliertypesettings",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_supplier_types",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حُدث بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="suppliertype",
            name="settings",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplier_type",
                to="supplier.suppliertypesettings",
                verbose_name="إعدادات النوع",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="suppliers_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="financial_account",
            field=models.OneToOneField(
                blank=True,
                help_text="الحساب المحاسبي المرتبط بهذا المورد في دليل الحسابات",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplier",
                to="financial.chartofaccounts",
                verbose_name="الحساب المحاسبي",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="primary_type",
            field=models.ForeignKey(
                help_text="تصنيف المورد حسب نوع الخدمة المقدمة",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="suppliers",
                to="supplier.suppliertype",
                verbose_name="نوع المورد",
            ),
        ),
        migrations.AddField(
            model_name="monthlydriverinvoice",
            name="driver_supplier",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True, "primary_type__code": "driver"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monthly_invoices",
                to="supplier.supplier",
                verbose_name="السائق (مورد)",
            ),
        ),
        migrations.AddField(
            model_name="monthlydriverinvoice",
            name="generated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="monthly_driver_invoices_generated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشأت بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="monthlydriverinvoice",
            name="purchase_invoice",
            field=models.OneToOneField(
                blank=True,
                help_text="فاتورة المشتريات المرتبطة في نظام الموردين",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="monthly_driver_invoice",
                to="purchase.purchase",
                verbose_name="فاتورة المشتريات",
            ),
        ),
        migrations.AddField(
            model_name="driverpricinghistory",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="driver_pricing_changes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="driverpricinghistory",
            name="driver_supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricing_history",
                to="supplier.supplier",
                verbose_name="السائق (مورد)",
            ),
        ),
        migrations.AddIndex(
            model_name="monthlydriverinvoice",
            index=models.Index(
                fields=["driver_supplier"], name="supplier_mo_driver__1fff05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monthlydriverinvoice",
            index=models.Index(
                fields=["month", "year"], name="supplier_mo_month_8e9ba8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monthlydriverinvoice",
            index=models.Index(fields=["status"], name="supplier_mo_status_4c3def_idx"),
        ),
        migrations.AddIndex(
            model_name="monthlydriverinvoice",
            index=models.Index(
                fields=["generated_at"], name="supplier_mo_generat_a95b22_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="monthlydriverinvoice",
            unique_together={("driver_supplier", "month", "year")},
        ),
        migrations.AddIndex(
            model_name="driverpricinghistory",
            index=models.Index(
                fields=["driver_supplier"], name="supplier_dr_driver__d75a3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="driverpricinghistory",
            index=models.Index(
                fields=["effective_date"], name="supplier_dr_effecti_4510da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="driverpricinghistory",
            index=models.Index(
                fields=["created_at"], name="supplier_dr_created_1229c2_idx"
            ),
        ),
    ]
