# Generated by Django 4.2.26 on 2026-02-27 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("financial", "0001_initial"),
        ("supplier", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="suppliertypesettings",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_supplier_types",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="suppliertypesettings",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_supplier_types",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حُدث بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="suppliertype",
            name="settings",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplier_type",
                to="supplier.suppliertypesettings",
                verbose_name="إعدادات النوع",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="suppliers_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="financial_account",
            field=models.OneToOneField(
                blank=True,
                help_text="الحساب المحاسبي المرتبط بهذا المورد في دليل الحسابات",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplier",
                to="financial.chartofaccounts",
                verbose_name="الحساب المحاسبي",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="primary_type",
            field=models.ForeignKey(
                help_text="تصنيف المورد حسب نوع الخدمة المقدمة",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="suppliers",
                to="supplier.suppliertype",
                verbose_name="نوع المورد",
            ),
        ),
    ]
