# Generated by Django 4.2.26 on 2026-02-26 15:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("supplier", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MonthlyDriverInvoice",
        ),
    ]
