# Generated by Django 4.2.26 on 2026-02-26 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("supplier", "0003_remove_driver_models"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DriverPricingHistory",
        ),
    ]
