# Generated by Django 4.2.26 on 2026-02-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sale", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="payment_method",
            field=models.CharField(
                help_text="طريقة الدفع أو كود الحساب المالي",
                max_length=50,
                verbose_name="طريقة الدفع",
            ),
        ),
        migrations.AlterField(
            model_name="salepayment",
            name="payment_method",
            field=models.CharField(
                help_text="طريقة الدفع أو كود الحساب المالي",
                max_length=50,
                verbose_name="طريقة الدفع",
            ),
        ),
    ]
